2020-08-15 12:39:04,718 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-08-15 12:40:50,360 - werkzeug - INFO - 127.0.0.1 - - [15/Aug/2020 12:40:50] "GET / HTTP/1.1" 200 -
2020-08-15 12:41:03,863 - werkzeug - INFO - 127.0.0.1 - - [15/Aug/2020 12:41:03] "GET /favicon.ico HTTP/1.1" 404 -
2020-08-15 13:53:56,585 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-08-17 09:51:46,168 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-08-18 10:36:31,149 - __main__ - INFO - Added <bound method Client.get_firstname of <queenroxxanes.models.users.Client object at 0x10a2c6af0>> ,Username: <bound method User.get_username of <queenroxxanes.models.users.Client object at 0x10a2c6af0>>
2020-08-18 10:36:31,615 - __main__ - INFO - Added <bound method User.get_username of <queenroxxanes.models.users.Manager object at 0x10a3472b0>>
2020-08-18 10:44:39,609 - __main__ - INFO - Added <bound method Client.get_firstname of <queenroxxanes.models.users.Client object at 0x1033ad820>> ,Username: <bound method User.get_username of <queenroxxanes.models.users.Client object at 0x1033ad820>>
2020-08-18 10:44:39,737 - __main__ - INFO - Added <bound method User.get_username of <queenroxxanes.models.users.Manager object at 0x10342ef40>>
2020-08-18 10:44:39,862 - __main__ - INFO - Added appointment 1, <bound method Appointment.get_appointment_type of <queenroxxanes.models.appointments.Appointment object at 0x103436d60>>
2020-08-19 16:20:23,883 - __main__ - INFO - Added <bound method Client.get_firstname of <queenroxxanes.models.users.Client object at 0x1076d17c0>> ,Username: <bound method User.get_username of <queenroxxanes.models.users.Client object at 0x1076d17c0>>
2020-08-19 16:20:24,041 - __main__ - INFO - Added <bound method User.get_username of <queenroxxanes.models.users.Manager object at 0x107749880>>
2020-08-19 16:23:58,102 - __main__ - INFO - Added <bound method Client.get_firstname of <queenroxxanes.models.users.Client object at 0x109d8f7c0>> ,Username: <bound method User.get_username of <queenroxxanes.models.users.Client object at 0x109d8f7c0>>
2020-08-19 16:23:58,220 - __main__ - INFO - Added <bound method User.get_username of <queenroxxanes.models.users.Manager object at 0x109e02ee0>>
2020-08-19 16:23:58,348 - __main__ - INFO - Added appointment 1, <bound method Appointment.get_appointment_type of <queenroxxanes.models.appointments.Appointment object at 0x109e09e80>>
2020-08-20 15:05:41,634 - __main__ - INFO - Added <bound method Client.get_firstname of <queenroxxanes.models.users.Client object at 0x10962d7c0>> ,Username: <bound method User.get_username of <queenroxxanes.models.users.Client object at 0x10962d7c0>>
2020-08-20 15:05:41,812 - __main__ - INFO - Added <bound method User.get_username of <queenroxxanes.models.users.Manager object at 0x1096a6880>>
2020-08-20 15:05:41,936 - __main__ - INFO - Added appointment 1, <bound method Appointment.get_appointment_type of <queenroxxanes.models.appointments.Appointment object at 0x1096b6ac0>>
2020-08-21 13:34:04,410 - __main__ - INFO - Added <bound method Client.get_firstname of <queenroxxanes.models.users.Client object at 0x1107467f0>> ,Username: <bound method User.get_username of <queenroxxanes.models.users.Client object at 0x1107467f0>>
2020-08-21 13:34:04,536 - __main__ - INFO - Added <bound method User.get_username of <queenroxxanes.models.users.Manager object at 0x1107cbf10>>
2020-08-21 13:34:47,216 - __main__ - INFO - Added <bound method Client.get_firstname of <queenroxxanes.models.users.Client object at 0x1107827c0>> ,Username: <bound method User.get_username of <queenroxxanes.models.users.Client object at 0x1107827c0>>
2020-08-21 13:34:47,336 - __main__ - INFO - Added <bound method User.get_username of <queenroxxanes.models.users.Manager object at 0x1108043d0>>
2020-08-21 13:54:30,368 - __main__ - INFO - Added <bound method Client.get_firstname of <queenroxxanes.models.users.Client object at 0x110cdb7f0>> ,Username: <bound method User.get_username of <queenroxxanes.models.users.Client object at 0x110cdb7f0>>
2020-08-21 13:54:30,516 - __main__ - INFO - Added <bound method User.get_username of <queenroxxanes.models.users.Manager object at 0x110d60f10>>
2020-08-21 14:03:37,643 - __main__ - INFO - Added <bound method Client.get_firstname of <queenroxxanes.models.users.Client object at 0x101eee7f0>> ,Username: <bound method User.get_username of <queenroxxanes.models.users.Client object at 0x101eee7f0>>
2020-08-21 14:03:37,767 - __main__ - INFO - Added <bound method User.get_username of <queenroxxanes.models.users.Manager object at 0x101f6a8b0>>
2020-08-21 14:03:38,014 - __main__ - ERROR - Encountered an error: 'NoneType' object is not callable
2020-08-21 14:08:49,063 - __main__ - INFO - Added <bound method Client.get_firstname of <queenroxxanes.models.users.Client object at 0x1023047f0>> ,Username: <bound method User.get_username of <queenroxxanes.models.users.Client object at 0x1023047f0>>
2020-08-21 14:08:49,210 - __main__ - INFO - Added <bound method User.get_username of <queenroxxanes.models.users.Manager object at 0x10238af10>>
2020-08-21 14:08:49,448 - __main__ - ERROR - Encountered an error: 'NoneType' object is not callable
2020-08-21 14:08:49,448 - __main__ - INFO - Added appointment 1, <bound method Appointment.get_appointment_type of <queenroxxanes.models.appointments.Appointment object at 0x102391d30>>
2020-08-21 14:11:31,198 - __main__ - INFO - Added <bound method Client.get_firstname of <queenroxxanes.models.users.Client object at 0x110408400>> ,Username: <bound method User.get_username of <queenroxxanes.models.users.Client object at 0x110408400>>
2020-08-21 14:11:31,362 - __main__ - INFO - Added <bound method User.get_username of <queenroxxanes.models.users.Manager object at 0x11040ff70>>
2020-08-21 14:11:31,601 - __main__ - ERROR - Encountered an error: 'NoneType' object is not callable
2020-08-21 14:11:31,601 - __main__ - INFO - Added appointment 1, <bound method Appointment.get_appointment_type of <queenroxxanes.models.appointments.Appointment object at 0x11040ff40>>
2020-08-21 14:13:33,117 - __main__ - INFO - Added <bound method Client.get_firstname of <queenroxxanes.models.users.Client object at 0x105ecb7f0>> ,Username: <bound method User.get_username of <queenroxxanes.models.users.Client object at 0x105ecb7f0>>
2020-08-21 14:13:33,244 - __main__ - INFO - Added <bound method User.get_username of <queenroxxanes.models.users.Manager object at 0x105f468b0>>
2020-08-21 14:13:33,482 - __main__ - ERROR - Encountered an error: 'NoneType' object is not callable
2020-08-21 14:13:33,482 - __main__ - INFO - Added appointment 1, <bound method Appointment.get_appointment_type of <queenroxxanes.models.appointments.Appointment object at 0x105f58d30>>
2020-08-21 14:30:10,487 - __main__ - INFO - Added <bound method Client.get_firstname of <queenroxxanes.models.users.Client object at 0x10f97b7f0>> ,Username: <bound method User.get_username of <queenroxxanes.models.users.Client object at 0x10f97b7f0>>
2020-08-21 14:30:10,803 - __main__ - INFO - Added <bound method User.get_username of <queenroxxanes.models.users.Manager object at 0x10f9ff400>>
2020-08-21 14:30:11,096 - __main__ - INFO - Updated information for client ID 1
2020-08-21 14:30:11,096 - __main__ - INFO - Added appointment 1, <bound method Appointment.get_appointment_type of <queenroxxanes.models.appointments.Appointment object at 0x10fa06d30>>
2020-08-21 14:42:16,954 - __main__ - INFO - Added <bound method Client.get_firstname of <queenroxxanes.models.users.Client object at 0x10ea2f7f0>> ,Username: <bound method User.get_username of <queenroxxanes.models.users.Client object at 0x10ea2f7f0>>
2020-08-21 14:42:17,076 - __main__ - INFO - Added <bound method User.get_username of <queenroxxanes.models.users.Manager object at 0x10eab3400>>
2020-08-21 14:42:17,356 - __main__ - INFO - Updated information for client ID 1
2020-08-21 14:42:17,357 - __main__ - INFO - Added appointment 1, <bound method Appointment.get_appointment_type of <queenroxxanes.models.appointments.Appointment object at 0x10eabad30>>
2020-08-21 14:46:09,778 - __main__ - INFO - Added <bound method Client.get_firstname of <queenroxxanes.models.users.Client object at 0x1060b47f0>> ,Username: <bound method User.get_username of <queenroxxanes.models.users.Client object at 0x1060b47f0>>
2020-08-21 14:46:09,904 - __main__ - INFO - Added <bound method User.get_username of <queenroxxanes.models.users.Manager object at 0x10612f8b0>>
2020-08-21 14:46:10,191 - __main__ - INFO - Updated information for client ID 1
2020-08-21 14:46:10,192 - __main__ - INFO - Added appointment 1, <bound method Appointment.get_appointment_type of <queenroxxanes.models.appointments.Appointment object at 0x106140d00>>
2020-08-21 15:26:34,498 - __main__ - INFO - Added <bound method Client.get_firstname of <queenroxxanes.models.users.Client object at 0x10c6e27c0>> ,Username: <bound method User.get_username of <queenroxxanes.models.users.Client object at 0x10c6e27c0>>
2020-08-21 15:26:34,655 - __main__ - INFO - Added <bound method User.get_username of <queenroxxanes.models.users.Manager object at 0x10c74d880>>
2020-08-21 15:26:34,958 - __main__ - INFO - Updated information for client ID 1
2020-08-21 15:26:34,958 - __main__ - INFO - Added appointment 1, <bound method Appointment.get_appointment_type of <queenroxxanes.models.appointments.Appointment object at 0x10c75fd90>>
2020-08-22 13:57:47,708 - __main__ - INFO - Added <bound method Client.get_firstname of <queenroxxanes.models.users.Client object at 0x107a347c0>> ,Username: <bound method User.get_username of <queenroxxanes.models.users.Client object at 0x107a347c0>>
2020-08-22 13:57:47,835 - __main__ - INFO - Added <bound method User.get_username of <queenroxxanes.models.users.Manager object at 0x107aa9ee0>>
2020-08-22 13:57:48,121 - __main__ - INFO - Updated information for client ID 1
2020-08-22 13:57:48,121 - __main__ - INFO - Added appointment 1, <bound method Appointment.get_appointment_type of <queenroxxanes.models.appointments.Appointment object at 0x107ab0ca0>>
2020-08-22 14:51:07,754 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-08-22 14:51:37,151 - werkzeug - INFO - 127.0.0.1 - - [22/Aug/2020 14:51:37] "[37mGET / HTTP/1.1[0m" 200 -
2020-08-23 10:43:15,661 - __main__ - INFO - Added <bound method Client.get_firstname of <queenroxxanes.models.users.Client object at 0x10f9b3790>> ,Username: <bound method User.get_username of <queenroxxanes.models.users.Client object at 0x10f9b3790>>
2020-08-23 10:43:15,788 - __main__ - INFO - Added <bound method User.get_username of <queenroxxanes.models.users.Manager object at 0x10fa1d850>>
2020-08-23 10:43:16,062 - __main__ - INFO - Updated information for client ID 1
2020-08-23 10:43:16,062 - __main__ - INFO - Added appointment 1, <bound method Appointment.get_appointment_type of <queenroxxanes.models.appointments.Appointment object at 0x10fa2fd30>>
2020-08-24 11:09:48,604 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-08-24 16:20:29,966 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-08-24 16:50:47,688 - werkzeug - INFO - 127.0.0.1 - - [24/Aug/2020 16:50:47] "[31m[1mGET /users HTTP/1.1[0m" 401 -
2020-08-24 16:50:47,955 - werkzeug - INFO - 127.0.0.1 - - [24/Aug/2020 16:50:47] "[31m[1mGET /users HTTP/1.1[0m" 401 -
2020-08-24 17:58:43,278 - werkzeug - INFO - 127.0.0.1 - - [24/Aug/2020 17:58:43] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-24 17:58:44,315 - werkzeug - INFO - 127.0.0.1 - - [24/Aug/2020 17:58:44] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-24 17:58:54,715 - werkzeug - INFO - 127.0.0.1 - - [24/Aug/2020 17:58:54] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-24 17:58:54,721 - werkzeug - INFO - 127.0.0.1 - - [24/Aug/2020 17:58:54] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-24 17:59:12,140 - werkzeug - INFO - 127.0.0.1 - - [24/Aug/2020 17:59:12] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-24 17:59:12,212 - werkzeug - INFO - 127.0.0.1 - - [24/Aug/2020 17:59:12] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-24 17:59:25,467 - werkzeug - INFO - 127.0.0.1 - - [24/Aug/2020 17:59:25] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-24 17:59:25,552 - werkzeug - INFO - 127.0.0.1 - - [24/Aug/2020 17:59:25] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-24 18:00:06,138 - werkzeug - INFO - 127.0.0.1 - - [24/Aug/2020 18:00:06] "[31m[1mGET /users HTTP/1.1[0m" 401 -
2020-08-24 18:00:06,190 - werkzeug - INFO - 127.0.0.1 - - [24/Aug/2020 18:00:06] "[31m[1mGET /users HTTP/1.1[0m" 401 -
2020-08-24 18:00:28,668 - werkzeug - INFO - 127.0.0.1 - - [24/Aug/2020 18:00:28] "[31m[1mGET /users HTTP/1.1[0m" 401 -
2020-08-24 18:00:28,720 - werkzeug - INFO - 127.0.0.1 - - [24/Aug/2020 18:00:28] "[31m[1mGET /users HTTP/1.1[0m" 401 -
2020-08-24 18:01:53,249 - werkzeug - INFO - 127.0.0.1 - - [24/Aug/2020 18:01:53] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-24 18:01:53,345 - werkzeug - INFO - 127.0.0.1 - - [24/Aug/2020 18:01:53] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-24 18:02:23,569 - werkzeug - INFO - 127.0.0.1 - - [24/Aug/2020 18:02:23] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-24 18:02:23,589 - werkzeug - INFO - 127.0.0.1 - - [24/Aug/2020 18:02:23] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-24 18:06:49,432 - werkzeug - INFO - 127.0.0.1 - - [24/Aug/2020 18:06:49] "[31m[1mGET /users HTTP/1.1[0m" 401 -
2020-08-24 18:07:20,976 - werkzeug - INFO - 127.0.0.1 - - [24/Aug/2020 18:07:20] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-24 18:07:21,122 - werkzeug - INFO - 127.0.0.1 - - [24/Aug/2020 18:07:21] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-24 18:07:25,507 - werkzeug - INFO - 127.0.0.1 - - [24/Aug/2020 18:07:25] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-24 18:07:30,305 - werkzeug - INFO - 127.0.0.1 - - [24/Aug/2020 18:07:30] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-24 18:07:30,400 - werkzeug - INFO - 127.0.0.1 - - [24/Aug/2020 18:07:30] "[31m[1mPOST /users HTTP/1.1[0m" 401 -
2020-08-24 18:07:34,634 - werkzeug - INFO - 127.0.0.1 - - [24/Aug/2020 18:07:34] "[31m[1mPOST /users HTTP/1.1[0m" 401 -
2020-08-24 18:07:37,888 - werkzeug - INFO - 127.0.0.1 - - [24/Aug/2020 18:07:37] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-24 18:07:37,970 - werkzeug - INFO - 127.0.0.1 - - [24/Aug/2020 18:07:37] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-24 18:07:44,882 - werkzeug - INFO - 127.0.0.1 - - [24/Aug/2020 18:07:44] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-24 18:07:44,961 - werkzeug - INFO - 127.0.0.1 - - [24/Aug/2020 18:07:44] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-24 18:35:01,511 - werkzeug - INFO - 127.0.0.1 - - [24/Aug/2020 18:35:01] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-24 18:35:01,621 - werkzeug - INFO - 127.0.0.1 - - [24/Aug/2020 18:35:01] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-24 18:35:10,996 - werkzeug - INFO - 127.0.0.1 - - [24/Aug/2020 18:35:10] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-24 18:35:11,001 - werkzeug - INFO - 127.0.0.1 - - [24/Aug/2020 18:35:11] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-25 11:09:27,967 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-08-25 11:12:07,766 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 11:12:07] "[31m[1mGET /users HTTP/1.1[0m" 401 -
2020-08-25 11:12:31,443 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 11:12:31] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 11:12:32,015 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 11:12:32] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-25 11:13:00,139 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 11:13:00] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 11:13:00,166 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 11:13:00] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-25 11:13:04,981 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 11:13:04] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 11:13:05,050 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 11:13:05] "[31m[1mPOST /users HTTP/1.1[0m" 401 -
2020-08-25 11:13:19,347 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 11:13:19] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 11:13:19,419 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 11:13:19] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-25 11:13:22,875 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 11:13:22] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-25 11:24:42,508 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 11:24:42] "[31m[1mGET /users HTTP/1.1[0m" 401 -
2020-08-25 11:35:08,972 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 11:35:08] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 11:35:09,093 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 11:35:09] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-25 11:35:11,606 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 11:35:11] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-25 11:35:59,247 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 11:35:59] "[31m[1mGET /users HTTP/1.1[0m" 401 -
2020-08-25 11:36:11,707 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 11:36:11] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 11:36:11,803 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 11:36:11] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-25 11:38:15,192 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 11:38:15] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 11:38:15,222 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 11:38:15] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-25 11:44:31,150 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 11:44:31] "[31m[1mGET /users HTTP/1.1[0m" 401 -
2020-08-25 12:54:05,022 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 12:54:05] "[31m[1mGET /users HTTP/1.1[0m" 401 -
2020-08-25 13:09:41,101 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 13:09:41] "[31m[1mGET /users HTTP/1.1[0m" 401 -
2020-08-25 13:09:50,866 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 13:09:50] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 13:09:51,372 - queenroxxanes.app - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 23, in route_login
    user = login(user_username, user_password)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 126, in login
    if user_dict['password'] == password:
TypeError: 'NoneType' object is not subscriptable
2020-08-25 13:09:51,796 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 13:09:51] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-08-25 13:33:26,649 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 13:33:26] "[31m[1mGET /users HTTP/1.1[0m" 401 -
2020-08-25 13:33:36,914 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 13:33:36] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 13:33:37,048 - queenroxxanes.app - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 23, in route_login
    user = login(user_username, user_password)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 126, in login
    if user_dict['password'] == password:
TypeError: 'NoneType' object is not subscriptable
2020-08-25 13:33:37,051 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 13:33:37] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-08-25 13:34:03,934 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 13:34:03] "[37mOPTIONS /register HTTP/1.1[0m" 200 -
2020-08-25 13:34:04,689 - queenroxxanes.data.db - INFO - Added <bound method Client.get_firstname of <queenroxxanes.models.users.Client object at 0x10713a670>> ,Username: <bound method User.get_username of <queenroxxanes.models.users.Client object at 0x10713a670>>
2020-08-25 13:34:04,690 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 13:34:04] "[37mPOST /register HTTP/1.1[0m" 201 -
2020-08-25 13:40:18,945 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 13:40:18] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 13:40:19,188 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 13:40:19] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-25 13:40:39,900 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 13:40:39] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 13:40:39,939 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 13:40:39] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-25 13:40:51,935 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 13:40:51] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 13:40:52,051 - queenroxxanes.app - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 23, in route_login
    user = login(user_username, user_password)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 126, in login
    if user_dict['password'] == password:
TypeError: 'NoneType' object is not subscriptable
2020-08-25 13:40:52,185 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 13:40:52] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-08-25 13:41:09,240 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 13:41:09] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 13:41:09,327 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 13:41:09] "[31m[1mPOST /users HTTP/1.1[0m" 401 -
2020-08-25 13:41:12,435 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 13:41:12] "[31m[1mPOST /users HTTP/1.1[0m" 401 -
2020-08-25 13:41:20,360 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 13:41:20] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 13:41:20,431 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 13:41:20] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-25 13:41:45,799 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 13:41:45] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 13:41:45,827 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 13:41:45] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-25 13:43:55,191 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 13:43:55] "[31m[1mGET /users HTTP/1.1[0m" 401 -
2020-08-25 13:43:57,136 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 13:43:57] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 13:43:57,219 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 13:43:57] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-25 13:44:15,735 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 13:44:15] "[37mOPTIONS /register HTTP/1.1[0m" 200 -
2020-08-25 13:44:15,956 - queenroxxanes.data.db - ERROR - E11000 duplicate key error collection: queenroxxanes.users index: username_1 dup key: { username: "" }, full error: {'index': 0, 'code': 11000, 'keyPattern': {'username': 1}, 'keyValue': {'username': ''}, 'errmsg': 'E11000 duplicate key error collection: queenroxxanes.users index: username_1 dup key: { username: "" }'}
2020-08-25 13:44:15,956 - queenroxxanes.data.db - INFO - Added <bound method Client.get_firstname of <queenroxxanes.models.users.Client object at 0x10713a580>> ,Username: <bound method User.get_username of <queenroxxanes.models.users.Client object at 0x10713a580>>
2020-08-25 13:44:15,958 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 13:44:15] "[31m[1mPOST /register HTTP/1.1[0m" 400 -
2020-08-25 13:44:23,463 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 13:44:23] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 13:44:23,469 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 13:44:23] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-25 13:44:25,509 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 13:44:25] "[37mOPTIONS /register HTTP/1.1[0m" 200 -
2020-08-25 13:44:25,680 - queenroxxanes.data.db - ERROR - E11000 duplicate key error collection: queenroxxanes.users index: username_1 dup key: { username: "" }, full error: {'index': 0, 'code': 11000, 'keyPattern': {'username': 1}, 'keyValue': {'username': ''}, 'errmsg': 'E11000 duplicate key error collection: queenroxxanes.users index: username_1 dup key: { username: "" }'}
2020-08-25 13:44:25,680 - queenroxxanes.data.db - INFO - Added <bound method Client.get_firstname of <queenroxxanes.models.users.Client object at 0x10713af10>> ,Username: <bound method User.get_username of <queenroxxanes.models.users.Client object at 0x10713af10>>
2020-08-25 13:44:25,682 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 13:44:25] "[31m[1mPOST /register HTTP/1.1[0m" 400 -
2020-08-25 13:44:45,852 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 13:44:45] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 13:44:45,989 - queenroxxanes.app - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 23, in route_login
    user = login(user_username, user_password)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 126, in login
    if user_dict['password'] == password:
TypeError: 'NoneType' object is not subscriptable
2020-08-25 13:44:45,992 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 13:44:45] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-08-25 13:44:56,118 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 13:44:56] "[37mOPTIONS /register HTTP/1.1[0m" 200 -
2020-08-25 13:44:56,254 - queenroxxanes.data.db - ERROR - E11000 duplicate key error collection: queenroxxanes.users index: username_1 dup key: { username: "" }, full error: {'index': 0, 'code': 11000, 'keyPattern': {'username': 1}, 'keyValue': {'username': ''}, 'errmsg': 'E11000 duplicate key error collection: queenroxxanes.users index: username_1 dup key: { username: "" }'}
2020-08-25 13:44:56,255 - queenroxxanes.data.db - INFO - Added <bound method Client.get_firstname of <queenroxxanes.models.users.Client object at 0x1070bd160>> ,Username: <bound method User.get_username of <queenroxxanes.models.users.Client object at 0x1070bd160>>
2020-08-25 13:44:56,256 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 13:44:56] "[31m[1mPOST /register HTTP/1.1[0m" 400 -
2020-08-25 14:23:38,492 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:23:38] "[31m[1mGET /users HTTP/1.1[0m" 401 -
2020-08-25 14:23:38,428 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:23:38] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 14:23:40,097 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:23:40] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-25 14:23:53,834 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:23:53] "[37mGET /users HTTP/1.1[0m" 200 -
2020-08-25 14:23:55,036 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:23:55] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 14:23:55,042 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:23:55] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-25 14:23:58,413 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:23:58] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 14:23:58,507 - queenroxxanes.app - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 23, in route_login
    user = login(user_username, user_password)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 126, in login
    if user_dict['password'] == password:
TypeError: 'NoneType' object is not subscriptable
2020-08-25 14:23:58,604 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:23:58] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-08-25 14:24:09,648 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:24:09] "[37mOPTIONS /register HTTP/1.1[0m" 200 -
2020-08-25 14:24:09,804 - queenroxxanes.data.db - ERROR - E11000 duplicate key error collection: queenroxxanes.users index: username_1 dup key: { username: "" }, full error: {'index': 0, 'code': 11000, 'keyPattern': {'username': 1}, 'keyValue': {'username': ''}, 'errmsg': 'E11000 duplicate key error collection: queenroxxanes.users index: username_1 dup key: { username: "" }'}
2020-08-25 14:24:09,805 - queenroxxanes.data.db - INFO - Added <bound method Client.get_firstname of <queenroxxanes.models.users.Client object at 0x1070e6400>> ,Username: <bound method User.get_username of <queenroxxanes.models.users.Client object at 0x1070e6400>>
2020-08-25 14:24:09,819 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:24:09] "[31m[1mPOST /register HTTP/1.1[0m" 400 -
2020-08-25 14:24:16,369 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:24:16] "[37mOPTIONS /register HTTP/1.1[0m" 200 -
2020-08-25 14:24:16,513 - queenroxxanes.data.db - ERROR - E11000 duplicate key error collection: queenroxxanes.users index: username_1 dup key: { username: "" }, full error: {'index': 0, 'code': 11000, 'keyPattern': {'username': 1}, 'keyValue': {'username': ''}, 'errmsg': 'E11000 duplicate key error collection: queenroxxanes.users index: username_1 dup key: { username: "" }'}
2020-08-25 14:24:16,514 - queenroxxanes.data.db - INFO - Added <bound method Client.get_firstname of <queenroxxanes.models.users.Client object at 0x1070e6400>> ,Username: <bound method User.get_username of <queenroxxanes.models.users.Client object at 0x1070e6400>>
2020-08-25 14:24:16,515 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:24:16] "[31m[1mPOST /register HTTP/1.1[0m" 400 -
2020-08-25 14:25:24,799 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:25:24] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 14:25:24,926 - queenroxxanes.app - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 23, in route_login
    user = login(user_username, user_password)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 126, in login
    if user_dict['password'] == password:
TypeError: 'NoneType' object is not subscriptable
2020-08-25 14:25:24,977 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:25:24] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-08-25 14:25:37,282 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:25:37] "[37mOPTIONS /register HTTP/1.1[0m" 200 -
2020-08-25 14:25:37,426 - queenroxxanes.data.db - ERROR - E11000 duplicate key error collection: queenroxxanes.users index: username_1 dup key: { username: "" }, full error: {'index': 0, 'code': 11000, 'keyPattern': {'username': 1}, 'keyValue': {'username': ''}, 'errmsg': 'E11000 duplicate key error collection: queenroxxanes.users index: username_1 dup key: { username: "" }'}
2020-08-25 14:25:37,427 - queenroxxanes.data.db - INFO - Added <bound method Client.get_firstname of <queenroxxanes.models.users.Client object at 0x10705adf0>> ,Username: <bound method User.get_username of <queenroxxanes.models.users.Client object at 0x10705adf0>>
2020-08-25 14:25:37,428 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:25:37] "[31m[1mPOST /register HTTP/1.1[0m" 400 -
2020-08-25 14:32:45,355 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-08-25 14:34:50,973 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:34:50] "[31m[1mGET /users HTTP/1.1[0m" 401 -
2020-08-25 14:36:03,296 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:36:03] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 14:36:04,377 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:36:04] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-25 14:36:06,783 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:36:06] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-25 14:36:08,057 - queenroxxanes.app - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 23, in route_login
    user = login(user_username, user_password)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 126, in login
    if user_dict['password'] == password:
TypeError: 'NoneType' object is not subscriptable
2020-08-25 14:36:08,169 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:36:08] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-08-25 14:36:12,257 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:36:12] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 14:36:12,327 - queenroxxanes.app - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 23, in route_login
    user = login(user_username, user_password)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 126, in login
    if user_dict['password'] == password:
TypeError: 'NoneType' object is not subscriptable
2020-08-25 14:36:12,329 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:36:12] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-08-25 14:36:24,582 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:36:24] "[37mOPTIONS /register HTTP/1.1[0m" 200 -
2020-08-25 14:36:24,738 - queenroxxanes.data.db - INFO - Added <bound method Client.get_firstname of <queenroxxanes.models.users.Client object at 0x10b587490>> ,Username: <bound method User.get_username of <queenroxxanes.models.users.Client object at 0x10b587490>>
2020-08-25 14:36:24,740 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:36:24] "[37mPOST /register HTTP/1.1[0m" 201 -
2020-08-25 14:38:41,064 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:38:41] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 14:38:41,163 - queenroxxanes.app - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 23, in route_login
    user = login(user_username, user_password)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 126, in login
    if user_dict['password'] == password:
TypeError: 'NoneType' object is not subscriptable
2020-08-25 14:38:41,200 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:38:41] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-08-25 14:38:44,925 - queenroxxanes.app - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 23, in route_login
    user = login(user_username, user_password)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 126, in login
    if user_dict['password'] == password:
TypeError: 'NoneType' object is not subscriptable
2020-08-25 14:38:44,930 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:38:44] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-08-25 14:39:18,604 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:39:18] "[37mOPTIONS /register HTTP/1.1[0m" 200 -
2020-08-25 14:39:18,755 - queenroxxanes.data.db - INFO - Added <bound method Client.get_firstname of <queenroxxanes.models.users.Client object at 0x10b5f4be0>> ,Username: <bound method User.get_username of <queenroxxanes.models.users.Client object at 0x10b5f4be0>>
2020-08-25 14:39:18,757 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:39:18] "[37mPOST /register HTTP/1.1[0m" 201 -
2020-08-25 14:39:36,554 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:39:36] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 14:39:36,698 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:39:36] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-25 14:40:36,440 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:40:36] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 14:40:36,462 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:40:36] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-25 14:44:19,023 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:44:19] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 14:44:19,114 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:44:19] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-25 14:44:35,837 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:44:35] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 14:44:35,878 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:44:35] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-25 14:44:49,507 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:44:49] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 14:44:49,609 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:44:49] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-25 14:45:17,650 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:45:17] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 14:45:17,674 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 14:45:17] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-25 17:01:52,455 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-08-25 17:05:50,209 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 17:05:50] "[31m[1mGET /users HTTP/1.1[0m" 401 -
2020-08-25 17:06:28,274 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 17:06:28] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 17:06:28,901 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 17:06:28] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-25 17:09:18,728 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 17:09:18] "[37mOPTIONS /register HTTP/1.1[0m" 200 -
2020-08-25 17:09:18,915 - queenroxxanes.data.db - INFO - Added <bound method Client.get_firstname of <queenroxxanes.models.users.Client object at 0x1101541f0>> ,Username: <bound method User.get_username of <queenroxxanes.models.users.Client object at 0x1101541f0>>
2020-08-25 17:09:18,917 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 17:09:18] "[37mPOST /register HTTP/1.1[0m" 201 -
2020-08-25 17:09:27,981 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 17:09:27] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 17:09:28,006 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 17:09:28] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-25 17:09:36,452 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 17:09:36] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 17:09:36,542 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 17:09:36] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-25 17:10:20,608 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 17:10:20] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 17:10:20,651 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 17:10:20] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-25 18:16:27,614 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 18:16:27] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 18:16:28,228 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 18:16:28] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-25 18:17:23,734 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 18:17:23] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 18:17:23,782 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 18:17:23] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-25 18:46:31,607 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 18:46:31] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 18:46:31,789 - queenroxxanes.app - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 23, in route_login
    user = login(user_username, user_password)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 126, in login
    if user_dict['password'] == password:
TypeError: 'NoneType' object is not subscriptable
2020-08-25 18:46:32,048 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 18:46:32] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-08-25 20:06:05,782 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 20:06:05] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 20:06:06,403 - queenroxxanes.app - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 23, in route_login
    user = login(user_username, user_password)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 126, in login
    if user_dict['password'] == password:
TypeError: 'NoneType' object is not subscriptable
2020-08-25 20:06:06,435 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 20:06:06] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-08-25 20:06:17,179 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 20:06:17] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 20:06:17,272 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 20:06:17] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-25 20:06:28,344 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 20:06:28] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-25 20:06:28,354 - werkzeug - INFO - 127.0.0.1 - - [25/Aug/2020 20:06:28] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-26 12:36:05,336 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 12:36:05] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-26 12:36:07,183 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 12:36:07] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-26 12:37:44,090 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 12:37:44] "[37mGET /users HTTP/1.1[0m" 200 -
2020-08-26 12:38:32,524 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 12:38:32] "[37mGET /users HTTP/1.1[0m" 200 -
2020-08-26 12:38:40,051 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 12:38:40] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-26 12:38:40,058 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 12:38:40] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-26 12:38:41,682 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 12:38:41] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-26 12:38:41,868 - queenroxxanes.app - ERROR - Exception on /users [POST]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 23, in route_login
    user = login(user_username, user_password)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 126, in login
    if user_dict['password'] == password:
TypeError: 'NoneType' object is not subscriptable
2020-08-26 12:38:41,997 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 12:38:41] "[35m[1mPOST /users HTTP/1.1[0m" 500 -
2020-08-26 12:39:01,742 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 12:39:01] "[37mOPTIONS /register HTTP/1.1[0m" 200 -
2020-08-26 12:39:02,062 - queenroxxanes.data.db - INFO - Added <bound method Client.get_firstname of <queenroxxanes.models.users.Client object at 0x1101d0850>> ,Username: <bound method User.get_username of <queenroxxanes.models.users.Client object at 0x1101d0850>>
2020-08-26 12:39:02,064 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 12:39:02] "[37mPOST /register HTTP/1.1[0m" 201 -
2020-08-26 12:39:08,749 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 12:39:08] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-26 12:39:08,861 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 12:39:08] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-26 12:47:38,935 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 12:47:38] "[37mGET /users HTTP/1.1[0m" 200 -
2020-08-26 12:47:51,485 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 12:47:51] "[37mGET /users HTTP/1.1[0m" 200 -
2020-08-26 12:47:58,410 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 12:47:58] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-26 12:47:58,460 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 12:47:58] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-26 12:48:01,049 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 12:48:01] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-26 12:48:01,118 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 12:48:01] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-26 12:48:18,481 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 12:48:18] "[37mOPTIONS /appointments HTTP/1.1[0m" 200 -
2020-08-26 12:48:19,588 - queenroxxanes.data.db - INFO - Updated information for client ID 13
2020-08-26 12:48:20,761 - queenroxxanes.data.db - INFO - Added appointment 2, <bound method Appointment.get_appointment_type of <queenroxxanes.models.appointments.Appointment object at 0x1100f2670>>
2020-08-26 12:48:20,763 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 12:48:20] "[37mPOST /appointments HTTP/1.1[0m" 201 -
2020-08-26 12:50:43,362 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 12:50:43] "[37mOPTIONS /appointments HTTP/1.1[0m" 200 -
2020-08-26 12:50:43,581 - queenroxxanes.app - ERROR - Exception on /appointments [POST]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/appointments.py", line 25, in appointments_main
    create_appointment(new_appointment)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 63, in create_appointment
    update_users_current_appointments(new_appointment.get_id(), new_appointment.get_client_id())
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 144, in update_users_current_appointments
    client_id = int(client_id)
ValueError: invalid literal for int() with base 10: ''
2020-08-26 12:50:43,640 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 12:50:43] "[35m[1mPOST /appointments HTTP/1.1[0m" 500 -
2020-08-26 12:51:46,853 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 12:51:46] "[37mOPTIONS /appointments HTTP/1.1[0m" 200 -
2020-08-26 12:51:47,193 - queenroxxanes.data.db - INFO - Updated information for client ID 13
2020-08-26 12:51:47,193 - queenroxxanes.data.db - INFO - Added appointment 4, <bound method Appointment.get_appointment_type of <queenroxxanes.models.appointments.Appointment object at 0x1101d0760>>
2020-08-26 12:51:47,195 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 12:51:47] "[37mPOST /appointments HTTP/1.1[0m" 201 -
2020-08-26 12:57:58,731 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 12:57:58] "[37mOPTIONS /appointments HTTP/1.1[0m" 200 -
2020-08-26 12:57:59,037 - queenroxxanes.data.db - INFO - Updated information for client ID 13
2020-08-26 12:57:59,038 - queenroxxanes.data.db - INFO - Added appointment 5, <bound method Appointment.get_appointment_type of <queenroxxanes.models.appointments.Appointment object at 0x1101d03d0>>
2020-08-26 12:57:59,101 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 12:57:59] "[37mPOST /appointments HTTP/1.1[0m" 201 -
2020-08-26 12:59:08,819 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 12:59:08] "[37mOPTIONS /appointments HTTP/1.1[0m" 200 -
2020-08-26 12:59:09,171 - queenroxxanes.data.db - INFO - Updated information for client ID 13
2020-08-26 12:59:09,171 - queenroxxanes.data.db - INFO - Added appointment 6, <bound method Appointment.get_appointment_type of <queenroxxanes.models.appointments.Appointment object at 0x1101d07c0>>
2020-08-26 12:59:09,172 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 12:59:09] "[37mPOST /appointments HTTP/1.1[0m" 201 -
2020-08-26 13:47:59,082 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:47:59] "[37mGET /users HTTP/1.1[0m" 200 -
2020-08-26 13:50:24,383 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:50:24] "[37mGET /users HTTP/1.1[0m" 200 -
2020-08-26 13:50:27,462 - queenroxxanes.router.users - INFO - GET request for appointment info of appointment history
2020-08-26 13:50:27,585 - queenroxxanes.app - ERROR - Exception on /users/current_appointments [GET]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 114, in route_current_appointments
    result = read_appointment_info_by_users_current_appointments(input_dict['_id'])
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 116, in read_appointment_info_by_users_current_appointments
    appt = read_appointment_by_id(int(appointment['_id']))
KeyError: '_id'
2020-08-26 13:50:27,588 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:50:27] "[35m[1mGET /users/current_appointments?_id=13 HTTP/1.1[0m" 500 -
2020-08-26 13:52:21,087 - queenroxxanes.router.users - INFO - GET request for appointment info of appointment history
2020-08-26 13:52:21,160 - queenroxxanes.app - ERROR - Exception on /users/current_appointments [GET]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 114, in route_current_appointments
    result = read_appointment_info_by_users_current_appointments(input_dict['_id'])
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 116, in read_appointment_info_by_users_current_appointments
    appt = read_appointment_by_id(int(appointment['_id']))
KeyError: '_id'
2020-08-26 13:52:21,218 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:52:21] "[35m[1mGET /users/current_appointments?_id=13 HTTP/1.1[0m" 500 -
2020-08-26 13:53:23,539 - queenroxxanes.router.users - INFO - GET request for appointment info of appointment history
2020-08-26 13:53:23,653 - queenroxxanes.app - ERROR - Exception on /users/current_appointments [GET]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 114, in route_current_appointments
    result = read_appointment_info_by_users_current_appointments(input_dict['_id'])
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 116, in read_appointment_info_by_users_current_appointments
    appt = read_appointment_by_id(int(appointment['_id']))
KeyError: '_id'
2020-08-26 13:53:23,688 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:53:23] "[35m[1mGET /users/current_appointments?_id=13 HTTP/1.1[0m" 500 -
2020-08-26 13:53:26,609 - queenroxxanes.router.users - INFO - GET request for appointment info of appointment history
2020-08-26 13:53:26,669 - queenroxxanes.app - ERROR - Exception on /users/current_appointments [GET]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 114, in route_current_appointments
    result = read_appointment_info_by_users_current_appointments(input_dict['_id'])
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 116, in read_appointment_info_by_users_current_appointments
    appt = read_appointment_by_id(int(appointment['_id']))
KeyError: '_id'
2020-08-26 13:53:26,672 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:53:26] "[35m[1mGET /users/current_appointments?_id=13 HTTP/1.1[0m" 500 -
2020-08-26 13:53:31,126 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:53:31] "[37mGET /users HTTP/1.1[0m" 200 -
2020-08-26 13:54:14,400 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:54:14] "[37mGET /users HTTP/1.1[0m" 200 -
2020-08-26 13:54:16,679 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:54:16] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-26 13:54:16,684 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:54:16] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-26 13:54:22,037 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:54:22] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-26 13:54:22,101 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:54:22] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-26 13:55:26,198 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:55:26] "[37mOPTIONS /register HTTP/1.1[0m" 200 -
2020-08-26 13:55:26,334 - queenroxxanes.data.db - INFO - Added <bound method Client.get_firstname of <queenroxxanes.models.users.Client object at 0x1101e1190>> ,Username: <bound method User.get_username of <queenroxxanes.models.users.Client object at 0x1101e1190>>
2020-08-26 13:55:26,335 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:55:26] "[37mPOST /register HTTP/1.1[0m" 201 -
2020-08-26 13:55:30,682 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:55:30] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-26 13:55:30,689 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:55:30] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-26 13:55:48,456 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:55:48] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-26 13:55:48,554 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:55:48] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-26 13:56:56,911 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:56:56] "[37mOPTIONS /appointments HTTP/1.1[0m" 200 -
2020-08-26 13:56:57,233 - queenroxxanes.data.db - INFO - Updated information for client ID 14
2020-08-26 13:56:57,233 - queenroxxanes.data.db - INFO - Added appointment 7, <bound method Appointment.get_appointment_type of <queenroxxanes.models.appointments.Appointment object at 0x1100f2b80>>
2020-08-26 13:56:57,235 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:56:57] "[37mPOST /appointments HTTP/1.1[0m" 201 -
2020-08-26 13:57:01,429 - queenroxxanes.router.users - INFO - GET request for appointment info of appointment history
2020-08-26 13:57:01,506 - queenroxxanes.app - ERROR - Exception on /users/current_appointments [GET]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 114, in route_current_appointments
    result = read_appointment_info_by_users_current_appointments(input_dict['_id'])
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 116, in read_appointment_info_by_users_current_appointments
    appt = read_appointment_by_id(int(appointment['_id']))
KeyError: '_id'
2020-08-26 13:57:01,636 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:57:01] "[35m[1mGET /users/current_appointments?_id=14 HTTP/1.1[0m" 500 -
2020-08-26 13:57:33,613 - queenroxxanes.router.users - INFO - GET request for appointment info of appointment history
2020-08-26 13:57:33,689 - queenroxxanes.app - ERROR - Exception on /users/current_appointments [GET]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 114, in route_current_appointments
    result = read_appointment_info_by_users_current_appointments(input_dict['_id'])
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 116, in read_appointment_info_by_users_current_appointments
    appt = read_appointment_by_id(int(appointment['_id']))
KeyError: '_id'
2020-08-26 13:57:33,693 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:57:33] "[35m[1mGET /users/current_appointments?_id=14 HTTP/1.1[0m" 500 -
2020-08-26 13:57:36,924 - queenroxxanes.router.users - INFO - GET request for appointment info of appointment history
2020-08-26 13:57:36,983 - queenroxxanes.app - ERROR - Exception on /users/current_appointments [GET]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 114, in route_current_appointments
    result = read_appointment_info_by_users_current_appointments(input_dict['_id'])
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 116, in read_appointment_info_by_users_current_appointments
    appt = read_appointment_by_id(int(appointment['_id']))
KeyError: '_id'
2020-08-26 13:57:36,985 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:57:36] "[35m[1mGET /users/current_appointments?_id=14 HTTP/1.1[0m" 500 -
2020-08-26 13:57:39,854 - queenroxxanes.router.users - INFO - GET request for appointment info of appointment history
2020-08-26 13:57:39,906 - queenroxxanes.app - ERROR - Exception on /users/current_appointments [GET]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 114, in route_current_appointments
    result = read_appointment_info_by_users_current_appointments(input_dict['_id'])
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 116, in read_appointment_info_by_users_current_appointments
    appt = read_appointment_by_id(int(appointment['_id']))
KeyError: '_id'
2020-08-26 13:57:39,908 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:57:39] "[35m[1mGET /users/current_appointments?_id=14 HTTP/1.1[0m" 500 -
2020-08-26 13:57:43,990 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:57:43] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-26 13:57:44,001 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:57:44] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-26 13:57:45,718 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:57:45] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-26 13:57:45,780 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:57:45] "[31m[1mPOST /users HTTP/1.1[0m" 401 -
2020-08-26 13:57:51,641 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:57:51] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-26 13:57:51,736 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:57:51] "[31m[1mPOST /users HTTP/1.1[0m" 401 -
2020-08-26 13:57:57,294 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:57:57] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-26 13:57:57,355 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:57:57] "[31m[1mPOST /users HTTP/1.1[0m" 401 -
2020-08-26 13:57:59,423 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:57:59] "[31m[1mPOST /users HTTP/1.1[0m" 401 -
2020-08-26 13:58:12,181 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:58:12] "[31m[1mGET /users HTTP/1.1[0m" 401 -
2020-08-26 13:58:14,400 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:58:14] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-26 13:58:14,523 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:58:14] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-26 13:58:16,346 - queenroxxanes.router.users - INFO - GET request for appointment info of appointment history
2020-08-26 13:58:16,400 - queenroxxanes.app - ERROR - Exception on /users/current_appointments [GET]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 114, in route_current_appointments
    result = read_appointment_info_by_users_current_appointments(input_dict['_id'])
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 116, in read_appointment_info_by_users_current_appointments
    appt = read_appointment_by_id(int(appointment['_id']))
KeyError: '_id'
2020-08-26 13:58:16,401 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 13:58:16] "[35m[1mGET /users/current_appointments?_id=14 HTTP/1.1[0m" 500 -
2020-08-26 14:00:29,562 - queenroxxanes.router.users - INFO - GET request for appointment info of appointment history
2020-08-26 14:00:29,642 - queenroxxanes.app - ERROR - Exception on /users/current_appointments [GET]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 114, in route_current_appointments
    result = read_appointment_info_by_users_current_appointments(input_dict['_id'])
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 116, in read_appointment_info_by_users_current_appointments
    appt = read_appointment_by_id(int(appointment['_id']))
KeyError: '_id'
2020-08-26 14:00:29,694 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 14:00:29] "[35m[1mGET /users/current_appointments?_id=14 HTTP/1.1[0m" 500 -
2020-08-26 14:00:33,293 - queenroxxanes.router.users - INFO - GET request for appointment info of appointment history
2020-08-26 14:00:33,351 - queenroxxanes.app - ERROR - Exception on /users/current_appointments [GET]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 114, in route_current_appointments
    result = read_appointment_info_by_users_current_appointments(input_dict['_id'])
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 116, in read_appointment_info_by_users_current_appointments
    appt = read_appointment_by_id(int(appointment['_id']))
KeyError: '_id'
2020-08-26 14:00:33,353 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 14:00:33] "[35m[1mGET /users/current_appointments?_id=14 HTTP/1.1[0m" 500 -
2020-08-26 14:00:38,839 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 14:00:38] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-26 14:00:38,877 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 14:00:38] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-26 14:00:52,376 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 14:00:52] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-26 14:00:52,457 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 14:00:52] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-26 14:00:54,178 - queenroxxanes.router.users - INFO - GET request for appointment info of appointment history
2020-08-26 14:00:54,232 - queenroxxanes.app - ERROR - Exception on /users/current_appointments [GET]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 114, in route_current_appointments
    result = read_appointment_info_by_users_current_appointments(input_dict['_id'])
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 116, in read_appointment_info_by_users_current_appointments
    appt = read_appointment_by_id(int(appointment['_id']))
KeyError: '_id'
2020-08-26 14:00:54,234 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 14:00:54] "[35m[1mGET /users/current_appointments?_id=14 HTTP/1.1[0m" 500 -
2020-08-26 14:00:55,944 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 14:00:55] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-26 14:01:00,170 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 14:01:00] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-26 14:01:00,232 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 14:01:00] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-26 14:01:15,399 - queenroxxanes.router.users - INFO - GET request for appointment info of appointment history
2020-08-26 14:01:15,543 - queenroxxanes.app - ERROR - Exception on /users/current_appointments [GET]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 114, in route_current_appointments
    result = read_appointment_info_by_users_current_appointments(input_dict['_id'])
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 116, in read_appointment_info_by_users_current_appointments
    appt = read_appointment_by_id(int(appointment['_id']))
KeyError: '_id'
2020-08-26 14:01:15,547 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 14:01:15] "[35m[1mGET /users/current_appointments?_id=13 HTTP/1.1[0m" 500 -
2020-08-26 14:01:18,873 - queenroxxanes.router.users - INFO - GET request for appointment info of appointment history
2020-08-26 14:01:18,940 - queenroxxanes.app - ERROR - Exception on /users/current_appointments [GET]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 114, in route_current_appointments
    result = read_appointment_info_by_users_current_appointments(input_dict['_id'])
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 116, in read_appointment_info_by_users_current_appointments
    appt = read_appointment_by_id(int(appointment['_id']))
KeyError: '_id'
2020-08-26 14:01:18,941 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 14:01:18] "[35m[1mGET /users/current_appointments?_id=13 HTTP/1.1[0m" 500 -
2020-08-26 14:01:23,915 - queenroxxanes.router.users - INFO - GET request for appointment info of appointment history
2020-08-26 14:01:24,005 - queenroxxanes.app - ERROR - Exception on /users/current_appointments [GET]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 114, in route_current_appointments
    result = read_appointment_info_by_users_current_appointments(input_dict['_id'])
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 116, in read_appointment_info_by_users_current_appointments
    appt = read_appointment_by_id(int(appointment['_id']))
KeyError: '_id'
2020-08-26 14:01:24,011 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 14:01:24] "[35m[1mGET /users/current_appointments?_id=13 HTTP/1.1[0m" 500 -
2020-08-26 14:01:25,288 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 14:01:25] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-26 14:01:25,296 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 14:01:25] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-26 14:01:42,725 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 14:01:42] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-26 14:01:42,811 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 14:01:42] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-26 14:01:48,647 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 14:01:48] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-26 14:01:48,653 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 14:01:48] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-26 19:13:53,111 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:13:53] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-26 19:13:54,139 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:13:54] "[31m[1mPOST /users HTTP/1.1[0m" 401 -
2020-08-26 19:14:01,777 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:14:01] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-26 19:14:01,842 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:14:01] "[31m[1mPOST /users HTTP/1.1[0m" 401 -
2020-08-26 19:14:11,534 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:14:11] "[31m[1mGET /users HTTP/1.1[0m" 401 -
2020-08-26 19:14:14,061 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:14:14] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-26 19:14:14,267 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:14:14] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-26 19:14:17,562 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:14:17] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-26 19:14:19,004 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:14:19] "[31m[1mPOST /users HTTP/1.1[0m" 401 -
2020-08-26 19:14:34,669 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:14:34] "[37mOPTIONS /register HTTP/1.1[0m" 200 -
2020-08-26 19:14:35,258 - queenroxxanes.data.db - INFO - Added <bound method Client.get_firstname of <queenroxxanes.models.users.Client object at 0x1101d0d90>> ,Username: <bound method User.get_username of <queenroxxanes.models.users.Client object at 0x1101d0d90>>
2020-08-26 19:14:35,331 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:14:35] "[37mPOST /register HTTP/1.1[0m" 201 -
2020-08-26 19:14:49,884 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:14:49] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-26 19:14:49,986 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:14:49] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-26 19:15:08,831 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:15:08] "[37mOPTIONS /appointments HTTP/1.1[0m" 200 -
2020-08-26 19:15:09,135 - queenroxxanes.data.db - INFO - Updated information for client ID 15
2020-08-26 19:15:09,135 - queenroxxanes.data.db - INFO - Added appointment 8, <bound method Appointment.get_appointment_type of <queenroxxanes.models.appointments.Appointment object at 0x1101d08e0>>
2020-08-26 19:15:09,136 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:15:09] "[37mPOST /appointments HTTP/1.1[0m" 201 -
2020-08-26 19:15:12,049 - queenroxxanes.router.users - INFO - GET request for appointment info of appointment history
2020-08-26 19:15:12,105 - queenroxxanes.app - ERROR - Exception on /users/current_appointments [GET]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 114, in route_current_appointments
    result = read_appointment_info_by_users_current_appointments(input_dict['_id'])
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 116, in read_appointment_info_by_users_current_appointments
    appt = read_appointment_by_id(int(appointment['_id']))
KeyError: '_id'
2020-08-26 19:15:12,410 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:15:12] "[35m[1mGET /users/current_appointments?_id=15 HTTP/1.1[0m" 500 -
2020-08-26 19:15:15,387 - queenroxxanes.router.users - INFO - GET request for appointment info of appointment history
2020-08-26 19:15:15,443 - queenroxxanes.app - ERROR - Exception on /users/current_appointments [GET]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 114, in route_current_appointments
    result = read_appointment_info_by_users_current_appointments(input_dict['_id'])
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 116, in read_appointment_info_by_users_current_appointments
    appt = read_appointment_by_id(int(appointment['_id']))
KeyError: '_id'
2020-08-26 19:15:15,445 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:15:15] "[35m[1mGET /users/current_appointments?_id=15 HTTP/1.1[0m" 500 -
2020-08-26 19:15:17,074 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:15:17] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-26 19:15:17,081 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:15:17] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-26 19:15:18,391 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:15:18] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-26 19:15:18,466 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:15:18] "[31m[1mPOST /users HTTP/1.1[0m" 401 -
2020-08-26 19:15:22,469 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:15:22] "[31m[1mGET /users HTTP/1.1[0m" 401 -
2020-08-26 19:15:34,302 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:15:34] "[31m[1mGET /users HTTP/1.1[0m" 401 -
2020-08-26 19:15:36,504 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:15:36] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-26 19:15:36,566 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:15:36] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-26 19:15:37,768 - queenroxxanes.router.users - INFO - GET request for appointment info of appointment history
2020-08-26 19:15:37,825 - queenroxxanes.app - ERROR - Exception on /users/current_appointments [GET]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 114, in route_current_appointments
    result = read_appointment_info_by_users_current_appointments(input_dict['_id'])
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 116, in read_appointment_info_by_users_current_appointments
    appt = read_appointment_by_id(int(appointment['_id']))
KeyError: '_id'
2020-08-26 19:15:37,828 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:15:37] "[35m[1mGET /users/current_appointments?_id=15 HTTP/1.1[0m" 500 -
2020-08-26 19:15:51,631 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:15:51] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-26 19:15:51,658 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:15:51] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-26 19:15:55,072 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:15:55] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-26 19:15:55,136 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:15:55] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-26 19:16:03,397 - queenroxxanes.router.users - INFO - GET request for appointment info of appointment history
2020-08-26 19:16:03,499 - queenroxxanes.app - ERROR - Exception on /users/current_appointments [GET]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 114, in route_current_appointments
    result = read_appointment_info_by_users_current_appointments(input_dict['_id'])
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 116, in read_appointment_info_by_users_current_appointments
    appt = read_appointment_by_id(int(appointment['_id']))
KeyError: '_id'
2020-08-26 19:16:03,501 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:16:03] "[35m[1mGET /users/current_appointments?_id=13 HTTP/1.1[0m" 500 -
2020-08-26 19:16:10,966 - queenroxxanes.router.users - INFO - GET request for appointment info of appointment history
2020-08-26 19:16:11,021 - queenroxxanes.app - ERROR - Exception on /users/current_appointments [GET]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 114, in route_current_appointments
    result = read_appointment_info_by_users_current_appointments(input_dict['_id'])
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 116, in read_appointment_info_by_users_current_appointments
    appt = read_appointment_by_id(int(appointment['_id']))
KeyError: '_id'
2020-08-26 19:16:11,022 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:16:11] "[35m[1mGET /users/current_appointments?_id=13 HTTP/1.1[0m" 500 -
2020-08-26 19:16:32,895 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:16:32] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-26 19:16:32,919 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:16:32] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-26 19:17:00,938 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:17:00] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-26 19:17:01,025 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:17:01] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-26 19:17:29,691 - queenroxxanes.router.users - INFO - GET request for appointment info of appointment history
2020-08-26 19:17:29,794 - queenroxxanes.app - ERROR - Exception on /users/current_appointments [GET]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 114, in route_current_appointments
    result = read_appointment_info_by_users_current_appointments(input_dict['_id'])
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 116, in read_appointment_info_by_users_current_appointments
    appt = read_appointment_by_id(int(appointment['_id']))
KeyError: '_id'
2020-08-26 19:17:29,906 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:17:29] "[35m[1mGET /users/current_appointments?_id=14 HTTP/1.1[0m" 500 -
2020-08-26 19:17:42,139 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:17:42] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-26 19:17:42,162 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:17:42] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-26 19:19:05,152 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:19:05] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-26 19:19:05,462 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:19:05] "[31m[1mPOST /users HTTP/1.1[0m" 401 -
2020-08-26 19:19:08,541 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:19:08] "[31m[1mPOST /users HTTP/1.1[0m" 401 -
2020-08-26 19:19:32,987 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:19:32] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-26 19:19:33,570 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:19:33] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-26 19:19:35,032 - queenroxxanes.router.users - INFO - GET request for appointment info of appointment history
2020-08-26 19:19:35,088 - queenroxxanes.app - ERROR - Exception on /users/current_appointments [GET]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 114, in route_current_appointments
    result = read_appointment_info_by_users_current_appointments(input_dict['_id'])
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 116, in read_appointment_info_by_users_current_appointments
    appt = read_appointment_by_id(int(appointment['_id']))
KeyError: '_id'
2020-08-26 19:19:35,124 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:19:35] "[35m[1mGET /users/current_appointments?_id=13 HTTP/1.1[0m" 500 -
2020-08-26 19:21:30,003 - queenroxxanes.router.users - INFO - GET request for appointment info of appointment history
2020-08-26 19:21:30,071 - queenroxxanes.app - ERROR - Exception on /users/current_appointments [GET]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 114, in route_current_appointments
    result = read_appointment_info_by_users_current_appointments(input_dict['_id'])
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 116, in read_appointment_info_by_users_current_appointments
    appt = read_appointment_by_id(int(appointment['_id']))
KeyError: '_id'
2020-08-26 19:21:30,096 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:21:30] "[35m[1mGET /users/current_appointments?_id=13 HTTP/1.1[0m" 500 -
2020-08-26 19:21:48,215 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:21:48] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-26 19:21:48,233 - werkzeug - INFO - 127.0.0.1 - - [26/Aug/2020 19:21:48] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-27 00:21:09,722 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 00:21:09] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-27 00:21:10,324 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 00:21:10] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-27 00:22:06,554 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 00:22:06] "[37mOPTIONS /appointments HTTP/1.1[0m" 200 -
2020-08-27 00:22:07,172 - queenroxxanes.data.db - INFO - Updated information for client ID 14
2020-08-27 00:22:07,172 - queenroxxanes.data.db - INFO - Added appointment 9, <bound method Appointment.get_appointment_type of <queenroxxanes.models.appointments.Appointment object at 0x1101eb6d0>>
2020-08-27 00:22:07,174 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 00:22:07] "[37mPOST /appointments HTTP/1.1[0m" 201 -
2020-08-27 00:22:14,187 - queenroxxanes.router.users - INFO - GET request for appointment info of appointment history
2020-08-27 00:22:14,307 - queenroxxanes.app - ERROR - Exception on /users/current_appointments [GET]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 114, in route_current_appointments
    result = read_appointment_info_by_users_current_appointments(input_dict['_id'])
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 116, in read_appointment_info_by_users_current_appointments
    appt = read_appointment_by_id(int(appointment['_id']))
KeyError: '_id'
2020-08-27 00:22:14,432 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 00:22:14] "[35m[1mGET /users/current_appointments?_id=14 HTTP/1.1[0m" 500 -
2020-08-27 00:22:22,019 - queenroxxanes.router.users - INFO - GET request for appointment info of appointment history
2020-08-27 00:22:22,076 - queenroxxanes.app - ERROR - Exception on /users/current_appointments [GET]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 114, in route_current_appointments
    result = read_appointment_info_by_users_current_appointments(input_dict['_id'])
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 116, in read_appointment_info_by_users_current_appointments
    appt = read_appointment_by_id(int(appointment['_id']))
KeyError: '_id'
2020-08-27 00:22:23,407 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 00:22:23] "[35m[1mGET /users/current_appointments?_id=14 HTTP/1.1[0m" 500 -
2020-08-27 00:22:31,739 - queenroxxanes.router.users - INFO - GET request for appointment info of appointment history
2020-08-27 00:22:31,794 - queenroxxanes.app - ERROR - Exception on /users/current_appointments [GET]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 114, in route_current_appointments
    result = read_appointment_info_by_users_current_appointments(input_dict['_id'])
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 116, in read_appointment_info_by_users_current_appointments
    appt = read_appointment_by_id(int(appointment['_id']))
KeyError: '_id'
2020-08-27 00:22:34,251 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 00:22:34] "[35m[1mGET /users/current_appointments?_id=14 HTTP/1.1[0m" 500 -
2020-08-27 00:22:36,030 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 00:22:36] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-27 00:22:36,042 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 00:22:36] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-27 00:22:42,575 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 00:22:42] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-27 00:22:42,906 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 00:22:42] "[31m[1mPOST /users HTTP/1.1[0m" 401 -
2020-08-27 00:22:50,508 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 00:22:50] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-27 00:22:50,575 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 00:22:50] "[31m[1mPOST /users HTTP/1.1[0m" 401 -
2020-08-27 00:22:52,354 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 00:22:52] "[31m[1mPOST /users HTTP/1.1[0m" 401 -
2020-08-27 00:23:11,876 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 00:23:11] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-27 00:23:12,120 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 00:23:12] "[31m[1mPOST /users HTTP/1.1[0m" 401 -
2020-08-27 00:23:14,670 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 00:23:14] "[31m[1mPOST /users HTTP/1.1[0m" 401 -
2020-08-27 00:23:15,312 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 00:23:15] "[31m[1mPOST /users HTTP/1.1[0m" 401 -
2020-08-27 00:23:26,284 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 00:23:26] "[31m[1mGET /users HTTP/1.1[0m" 401 -
2020-08-27 00:23:34,129 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 00:23:34] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-27 00:23:35,372 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 00:23:35] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-27 00:23:38,439 - queenroxxanes.router.users - INFO - GET request for appointment info of appointment history
2020-08-27 00:23:38,496 - queenroxxanes.app - ERROR - Exception on /users/current_appointments [GET]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 114, in route_current_appointments
    result = read_appointment_info_by_users_current_appointments(input_dict['_id'])
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 116, in read_appointment_info_by_users_current_appointments
    appt = read_appointment_by_id(int(appointment['_id']))
KeyError: '_id'
2020-08-27 00:23:38,498 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 00:23:38] "[35m[1mGET /users/current_appointments?_id=14 HTTP/1.1[0m" 500 -
2020-08-27 00:24:35,969 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 00:24:35] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-27 00:24:36,248 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 00:24:36] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-27 01:01:10,573 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 01:01:10] "[31m[1mGET /users HTTP/1.1[0m" 401 -
2020-08-27 01:01:51,132 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 01:01:51] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-27 01:01:51,578 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 01:01:51] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-27 01:01:53,529 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 01:01:53] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-27 01:01:59,298 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 01:01:59] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-27 01:01:59,405 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 01:01:59] "[31m[1mPOST /users HTTP/1.1[0m" 401 -
2020-08-27 01:02:02,826 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 01:02:02] "[31m[1mPOST /users HTTP/1.1[0m" 401 -
2020-08-27 01:02:08,002 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 01:02:08] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-27 01:02:08,070 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 01:02:08] "[31m[1mPOST /users HTTP/1.1[0m" 401 -
2020-08-27 01:07:37,893 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 01:07:37] "[31m[1mGET /users HTTP/1.1[0m" 401 -
2020-08-27 01:09:30,482 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 01:09:30] "[31m[1mGET /users HTTP/1.1[0m" 401 -
2020-08-27 01:09:47,537 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 01:09:47] "[31m[1mGET /users HTTP/1.1[0m" 401 -
2020-08-27 01:09:52,273 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 01:09:52] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-27 01:09:52,426 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 01:09:52] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-27 01:09:55,109 - queenroxxanes.router.users - INFO - GET request for appointment info of appointment history
2020-08-27 01:09:55,267 - queenroxxanes.app - ERROR - Exception on /users/current_appointments [GET]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 114, in route_current_appointments
    result = read_appointment_info_by_users_current_appointments(input_dict['_id'])
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 116, in read_appointment_info_by_users_current_appointments
    appt = read_appointment_by_id(int(appointment['_id']))
KeyError: '_id'
2020-08-27 01:09:55,364 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 01:09:55] "[35m[1mGET /users/current_appointments?_id=14 HTTP/1.1[0m" 500 -
2020-08-27 01:17:43,788 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 01:17:43] "[37mGET /users HTTP/1.1[0m" 200 -
2020-08-27 01:17:47,808 - queenroxxanes.router.users - INFO - GET request for appointment info of appointment history
2020-08-27 01:17:47,864 - queenroxxanes.app - ERROR - Exception on /users/current_appointments [GET]
Traceback (most recent call last):
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthewyeadon/.local/share/virtualenvs/myeadon2017-QGXdPE8A/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/router/users.py", line 114, in route_current_appointments
    result = read_appointment_info_by_users_current_appointments(input_dict['_id'])
  File "/Users/matthewyeadon/Documents/GitHub/myeadon2017/queenroxxanes/data/db.py", line 116, in read_appointment_info_by_users_current_appointments
    appt = read_appointment_by_id(int(appointment['_id']))
KeyError: '_id'
2020-08-27 01:17:47,867 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 01:17:47] "[35m[1mGET /users/current_appointments?_id=14 HTTP/1.1[0m" 500 -
2020-08-27 01:17:49,585 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 01:17:49] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-27 01:17:49,591 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 01:17:49] "[37mDELETE /users HTTP/1.1[0m" 204 -
2020-08-27 01:17:54,645 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 01:17:54] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-27 01:17:54,727 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 01:17:54] "[37mPOST /users HTTP/1.1[0m" 200 -
2020-08-27 01:21:06,716 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 01:21:06] "[37mGET /users HTTP/1.1[0m" 200 -
2020-08-27 10:05:53,121 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 10:05:53] "[37mOPTIONS /users HTTP/1.1[0m" 200 -
2020-08-27 10:05:53,520 - werkzeug - INFO - 127.0.0.1 - - [27/Aug/2020 10:05:53] "[37mDELETE /users HTTP/1.1[0m" 204 -
